sudo: true
language: python

env:
  - VARIANT=source/Hack-Regular.ufo
  - VARIANT=source/Hack-Bold.ufo
  - VARIANT=source/Hack-Italic.ufo
  - VARIANT=source/Hack-BoldItalic.ufo
  - SHELL_PATH=build.sh

before_script: 
  - pip install ufolint
  - sudo apt-get -qq update
  - sudo apt-get install -y shellcheck

script: 
  - "ufolint $VARIANT"
  - "shellcheck $SHELL_PATH"

notifications:
  email: false
