sudo: true
language: python

env:
  - TARGET="lint"
  - TARGET="build-with-dependencies"

matrix:
  include:
    - os: linux
      sudo: required
      before_script:
        - pip install ufolint
        - sudo apt-get -qq update
        - sudo apt-get install -y shellcheck
    - os: osx
      before_script:
        - brew update
        - brew install python
        - pip install shellcheck
        - brew outdated shellcheck || brew upgrade shellcheck

script:
  - make -j $TARGET

notifications:
  email: false
