sudo: true
language: python

env:
  - TARGET="lint"
  - TARGET="build-with-dependencies"

before_script:
  - pip install ufolint
  - sudo apt-get -qq update
  - sudo apt-get install -y shellcheck

script:
  - make -j $TARGET

notifications:
  email: false
