sudo: false
language: python

env:
  - VARIANT=source/Hack-Regular.ufo
  - VARIANT=source/Hack-Bold.ufo
  - VARIANT=source/Hack-Italic.ufo
  - VARIANT=source/Hack-BoldItalic.ufo

before_script: pip install ufolint

script: "ufolint $VARIANT"

notifications:
  email: false
