sudo: true
language: generic

env:
  - TARGET="lint"
  - TARGET="build-with-dependencies"

matrix:
  include:
    - os: linux
      sudo: required
      before_script:
        - pip install ufolint
        - sudo apt-get -qq update
        - sudo apt-get install -y shellcheck
      script:
        - make -j $TARGET
    - os: osx
      before_install:
        - brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
      before_script:
        - pip install ufolint
        - brew outdated shellcheck || brew upgrade shellcheck
      script:
        - make -j $TARGET


notifications:
  email: false
